import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { compileModule } from "svelte/compiler";
import ts from "typescript";
import { normalizeError } from "../lib/i18n/errors.ts";
import { galleryDateRange, galleryKey, galleryUrl, galleryViewerItems, galleryVisible } from "../lib/utils/gallery.ts";
import type { GalleryState } from "../lib/state/gallery.svelte";
import type { GalleryCursor, GalleryFilter, GalleryItem, GalleryPage, StoredMessage } from "../lib/utils/wire";

const message = (chat: string, id: string) => ({ chat, id, timestamp: 100, text: "caption", media_path: "/synthetic/image.png", media_thumb: "data:thumb", media_kind: "image", spoiler: false }) as StoredMessage;
const item = (chat: string, id: string): GalleryItem => ({ message: message(chat, id), urls: [] });

test("gallery dates include local end day; spoiler artwork/viewer and URL schemes stay gated", () => {
  assert.deepEqual(galleryDateRange("", ""), { since: null, until: null });
  const range = galleryDateRange("2026-09-30", "2026-09-30");
  assert.equal(range.since, Math.floor(new Date("2026-09-30T00:00:00").getTime() / 1000));
  assert.equal(range.until, Math.floor(new Date("2026-10-01T00:00:00").getTime() / 1000));
  assert.throws(() => galleryDateRange("2026-10-01", "2026-09-30"));
  assert.throws(() => galleryDateRange("not-a-date", ""));
  for (const url of ["javascript:alert(1)", "file:///synthetic/a", "mailto:a@test", "https://", "bad"]) assert.equal(galleryUrl(url), null);
  assert.equal(galleryUrl("https://synthetic.test/?a=1&b=2"), "https://synthetic.test/?a=1&b=2");
  const hidden = { ...item("a@s", "same"), message: { ...message("a@s", "same"), spoiler: true } };
  const ordinary = item("b@g.us", "same");
  const revealed = new Set<string>();
  assert.equal(galleryVisible(hidden.message, revealed), false);
  assert.deepEqual(galleryViewerItems([hidden, ordinary], revealed, () => "Peer").map((row) => row.id), [galleryKey(ordinary.message)]);
  revealed.add(galleryKey(hidden.message));
  assert.equal(galleryVisible(hidden.message, revealed), true);
  assert.equal(galleryViewerItems([hidden, ordinary], revealed, () => "Peer").length, 2);
  const round = { ...item("a@s", "round"), message: { ...message("a@s", "round"), media_kind: "round_video" } };
  assert.equal(galleryViewerItems([round], revealed, () => "Peer")[0].kind, "video");
});

test("gallery holds one page, composes filters, retries errors, and rejects stale account/filter results", async () => {
  const requests: { filter: GalleryFilter; cursor: GalleryCursor | null; limit: number; resolve: (page: GalleryPage) => void; reject: (error: Error) => void }[] = [];
  const fetch = (filter: GalleryFilter, cursor: GalleryCursor | null, limit: number) => new Promise<GalleryPage>((resolve, reject) => requests.push({ filter, cursor, limit, resolve, reject }));
  const source = readFileSync(new URL("../lib/state/gallery.svelte.ts", import.meta.url), "utf8");
  const js = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).outputText;
  const compiled = compileModule(js, { generate: "server", filename: "gallery.svelte.js" }).js.code.replace(/^import .*;$/gm, "").replace(/^export /gm, "");
  const State = new Function("normalizeError", `${compiled}\nreturn GalleryState;`)(normalizeError) as new (loader: typeof fetch) => GalleryState;
  const gallery = new State(fetch);
  const filter: GalleryFilter = { chat: "a@s", kind: "image", from_me: true, since: 100, until: 200 };
  const old = gallery.reset(filter);
  const current = gallery.reset({ ...filter, chat: null, kind: "link" });
  const cursor: GalleryCursor = { timestamp: 100, sort_order: 1, chat: "b@g.us", id: "same" };
  requests[1].resolve({ items: [item("b@g.us", "same")], next_cursor: cursor });
  await current;
  requests[0].reject(new Error("stale failure"));
  await old;
  assert.equal(gallery.error, null);
  assert.deepEqual(requests[1].filter, { ...filter, chat: null, kind: "link" });
  assert.equal(requests[1].limit, 60);
  const next = gallery.nextPage();
  await gallery.nextPage();
  assert.equal(requests.length, 3);
  assert.deepEqual(requests[2].cursor, cursor);
  requests[2].resolve({ items: [item("a@s", "older")], next_cursor: null });
  await next;
  assert.deepEqual(gallery.items.map((row) => row.message.id), ["older"]);
  assert.equal(gallery.pageIndex, 1);
  const previous = gallery.previousPage();
  requests[3].reject(new Error("offline"));
  await previous;
  assert.equal(gallery.pageIndex, 1);
  assert.equal(gallery.error, "Operation failed.");
  assert.match(gallery.diagnostic ?? "", /offline/);
  const retry = gallery.retry();
  assert.equal(requests[4].cursor, null);
  requests[4].resolve({ items: [item("b@g.us", "same")], next_cursor: cursor });
  await retry;
  assert.equal(gallery.pageIndex, 0);
  assert.equal(gallery.error, null);
  const pending = gallery.nextPage();
  gallery.resetAccount();
  requests[5].resolve({ items: [item("old-account@s", "private")], next_cursor: null });
  await pending;
  assert.deepEqual(gallery.items, []);
  assert.equal(gallery.loading, false);
});
