#!/usr/bin/env bash
#
# Regenerates THIRD_PARTY_NOTICES.md from the dependency metadata: Rust from
# cargo metadata, Node from pnpm, and a static list for the C libraries the
# AppImage bundles (they come from the system, not a package manager).
#
# For a fully bundled offline notice with every license text, cargo-about
# (https://github.com/EmbarkStudios/cargo-about) can produce it:
#
#   cargo install --locked --features cli cargo-about
#   cd src-tauri && cargo about init && cargo about generate about.hbs > license.html
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/THIRD_PARTY_NOTICES.md"

cargo metadata --format-version 1 --manifest-path "$ROOT/src-tauri/Cargo.toml" > "$OUT.meta.json"
(cd "$ROOT" && pnpm licenses list --json) > "$OUT.npm.json"

python3 - "$OUT" <<'PY'
import json, sys

out = sys.argv[1]
meta = json.load(open(out + ".meta.json"))
npm = json.load(open(out + ".npm.json"))

rust = sorted(
    (p["name"], p["version"], p.get("license") or "see the crate's repository")
    for p in meta["packages"]
    if p["name"] not in ("postal", "postal-core")
)

lines = [
    "# Third party notices",
    "",
    "Postal is MIT licensed (see LICENSE). It is built with the dependencies",
    "below, which keep their own licenses. Generated by scripts/licenses.sh.",
    "",
    "## Rust crates",
    "",
    f"{len(rust)} crates, mostly MIT or Apache-2.0. A few are MPL-2.0, which is",
    "file-level copyleft and does not affect this project's MIT license:",
    "cssparser, cssparser-macros, dtoa-short, option-ext, selectors.",
    "",
    "| Crate | Version | License |",
    "| --- | --- | --- |",
]
for name, ver, lic in rust:
    lines.append(f"| {name} | {ver} | {lic} |")

lines += ["", "## Node packages", "", "| Package | Version | License |", "| --- | --- | --- |"]
rows = []
for lic, pkgs in npm.items():
    for p in pkgs:
        versions = p.get("versions")
        ver = ", ".join(versions) if isinstance(versions, list) else ""
        rows.append((p.get("name", "?"), ver, lic))
for name, ver, lic in sorted(rows):
    lines.append(f"| {name} | {ver} | {lic} |")

# Hand-written because it is not a package: the flag font ships inside the
# country-flag-emoji-polyfill package and its glyphs are Twemoji artwork.
lines += [
    "",
    "## Bundled artwork",
    "",
    "Country flags on Windows are drawn with the \"Twemoji Country Flags\" font from",
    "country-flag-emoji-polyfill (TalkJS). Its glyphs are Twemoji graphics,",
    "Copyright Twitter, Inc and other contributors, used unmodified under",
    "CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/).",
    "Source: https://github.com/twitter/twemoji",
]

lines += [
    "",
    "## Bundled C libraries",
    "",
    "The AppImage bundles the GTK and WebKitGTK stack, which is separate from the",
    "Rust bindings above. These are used unmodified:",
    "",
    "| Library | License | Source |",
    "| --- | --- | --- |",
]
for name, lic, url in [
    ("WebKitGTK", "LGPL-2.1-or-later and BSD-2-Clause", "https://webkitgtk.org"),
    ("GTK", "LGPL-2.1-or-later", "https://gtk.org"),
    ("GLib", "LGPL-2.1-or-later", "https://gitlab.gnome.org/GNOME/glib"),
    ("gdk-pixbuf", "LGPL-2.1-or-later", "https://gitlab.gnome.org/GNOME/gdk-pixbuf"),
    ("Pango", "LGPL-2.1-or-later", "https://gitlab.gnome.org/GNOME/pango"),
    ("cairo", "LGPL-2.1-or-later or MPL-1.1", "https://cairographics.org"),
    ("HarfBuzz", "MIT", "https://harfbuzz.github.io"),
    ("libsoup", "LGPL-2.1-or-later", "https://gitlab.gnome.org/GNOME/libsoup"),
    ("GStreamer", "LGPL-2.1-or-later", "https://gstreamer.freedesktop.org"),
]:
    lines.append(f"| {name} | {lic} | {url} |")
lines += [
    "",
    "The LGPL libraries are dynamically linked. To relink against a modified",
    "version, replace the corresponding library in the AppImage's `usr/lib`.",
    "",
]

open(out, "w").write("\n".join(lines) + "\n")
print(f"wrote {out}")
PY

rm -f "$OUT.meta.json" "$OUT.npm.json"
